name: Backend SLSA generator

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    permissions:
      id-token: write
      contents: read
      actions: read

    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_nodejs_slsa3.yml@v2.1.0
    with:
      run-scripts: "ci, build"
