name: Frontend SSLA Generator

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  generate-slsa:
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_node_slsa3.yml@main
    with:
      build_root: frontend
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
