name: Generate SLSA Provenance for Frontend
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    permissions:
      id-token: write
      contents: read
      actions: read
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_nodejs_slsa3.yml@v2.1.0
    with:
      directory: front-end
      run-scripts: "ci, build"
  publish:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node registry authentication
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"
      - name: publish
        id: publish
        uses: slsa-framework/slsa-github-generator/actions/nodejs/publish@v2.1.0
        with:
          access: public
          node-auth-token: ${{ secrets.NPM_TOKEN }}
          package-name: ${{ needs.build.outputs.package-name }}
          package-download-name: ${{ needs.build.outputs.package-download-name }}
          package-download-sha256: ${{ needs.build.outputs.package-download-sha256 }}
          provenance-name: ${{ needs.build.outputs.provenance-name }}
          provenance-download-name: ${{ needs.build.outputs.provenance-download-name }}
          provenance-download-sha256: ${{ needs.build.outputs.provenance-download-sha256 }}
  verify:
    needs: [publish]
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts from the current workflow run
        uses: actions/download-artifact@v4

      - name: Find and move the package and provenance files
        run: |
          PACKAGE_FILE=$(find . -name "*.tgz" -print -quit)
          PROVENANCE_FILE=$(find . -name "*slsa-attestations" -print -quit)

          mv "$PACKAGE_FILE" ./package.tgz
          mv "$PROVENANCE_FILE" ./slsa-attestations

      - name: List files in the working directory
        run: ls -l

      - name: Verify SLSA Provenance
        run: |
          curl -LO https://github.com/slsa-framework/slsa-verifier/releases/latest/download/slsa-verifier-linux-amd64
          chmod +x slsa-verifier-linux-amd64
          ./slsa-verifier-linux-amd64 verify-artifact \
            --source-uri "https://github.com/${{ github.repository }}" \
            --source-branch "main" \
            --provenance-path slsa-attestations \
            package.tgz
