name: Generate SLSA Provenance for Backend

on:
  push:
    branches:
      - main
    paths:
      - "back-end/**"
  workflow_dispatch:

jobs:
  build:
    permissions:
      id-token: write
      contents: read
      actions: read
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_nodejs_slsa3.yml@v2.1.0
    with:
      directory: back-end
      run-scripts: "ci, test, build"

  publish:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node registry authentication
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"

      - name: publish
        id: publish
        uses: slsa-framework/slsa-github-generator/actions/nodejs/publish@v2.1.0
        with:
          access: public
          node-auth-token: ${{ secrets.NPM_TOKEN }}
          package-name: ${{ needs.build.outputs.package-name }}
          package-download-name: ${{ needs.build.outputs.package-download-name }}
          package-download-sha256: ${{ needs.build.outputs.package-download-sha256 }}
          provenance-name: ${{ needs.build.outputs.provenance-name }}
          provenance-download-name: ${{ needs.build.outputs.provenance-download-name }}
          provenance-download-sha256: ${{ needs.build.outputs.provenance-download-sha256 }}

  verify:
    needs: [publish]
    runs-on: ubuntu-latest
    steps:
      - name: Download package and attestation
        run: |
          curl -Sso attestations.json $(npm view @n4thanj/application-security-backend --json | jq -r '.dist.attestations.url')
          curl -Sso package.tgz "$(npm view @n4thanj/application-security-backend --json | jq -r '.dist.tarball')"
          mv package.tgz backend-package.tgz
          mv attestations.json backend-attestations.json

      - name: Verify SLSA Provenance
        run: |
          curl -LO https://github.com/slsa-framework/slsa-verifier/releases/latest/download/slsa-verifier-linux-amd64
          chmod +x slsa-verifier-linux-amd64
          SLSA_VERIFIER_EXPERIMENTAL=1 ./slsa-verifier-linux-amd64 verify-npm-package backend-package.tgz \
            --attestations-path backend-attestations.json \
            --builder-id "https://github.com/slsa-framework/slsa-github-generator/.github/workflows/builder_nodejs_slsa3.yml" \
            --package-name "@n4thanj/application-security-backend" \
            --package-version 1.0.0 \
            --source-uri github.com/N4thanJ/Application-Security

      - name: Upload verified backend artifacts
        uses: actions/upload-artifact@v3
        with:
          name: verified-backend
          path: |
            backend-package.tgz
            backend-attestations.json

release:
  needs: [verify]
  runs-on: ubuntu-latest
  steps:
    - uses: actions/download-artifact@v3
      with:
        name: verified-package
        path: .

    - uses: actions/download-artifact@v3
      with:
        name: verified-attestation
        path: .

    - name: Create backend-slsa folder and move files
      run: |
        mkdir backend-slsa
        mv package.tgz backend-slsa/backend-package.tgz
        mv attestations.json backend-slsa/backend-attestations.json

    - name: Zip the folder
      run: zip -r backend-slsa.zip backend-slsa

    - name: Upload release to GitHub
      uses: softprops/action-gh-release@v1
      with:
        files: backend-slsa.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
